version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/prometheus_fpgainfo_exporter"
    schedule:
      interval: "weekly"
