# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2024 Intel Corporation

FROM golang:1.21.5 as builder

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

COPY cmd/labeler/ cmd/labeler/
COPY pkg/ pkg/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o node_labeler cmd/labeler/main.go


RUN wget --progress=dot:giga https://pci-ids.ucw.cz/v2.2/pci.ids.gz -O pci.ids.gz && gunzip pci.ids.gz

FROM registry.access.redhat.com/ubi9/ubi-micro:9.4-6

ARG VERSION
### Required OpenShift Labels
LABEL name="Intel® FPGA discovery container" \
    vendor="Intel Corporation" \
    version=$VERSION \
    release="1" \
    summary="Intel® FPGA discovery container labels kubernetes nodes that include Intel® FPGA accelerator" \
    description="The container tries to detect Intel® FPGA accelerators and label the nodes that contain them \
and remove the label for nodes that do not."

RUN mkdir -p /usr/share/misc/

COPY --from=builder /workspace/pci.ids /usr/share/misc/pci.ids

COPY TEMP_LICENSE_COPY /licenses/LICENSE
USER 1001
WORKDIR /labeler-workspace
COPY --from=builder /workspace/node_labeler .

ENTRYPOINT ["bash", "-c", "/labeler-workspace/node_labeler && sleep infinity"]
