#!/bin/bash

IMAGE_REGISTRY=${N3000_IMAGE_REGISTRY:-registry.redhat.io}
SRIOV_FEC_DAEMON_VERSION=${SRIOV_FEC_DAEMON_VERSION:-v0.1.0}

export SRIOV_FEC_DAEMON_IMAGE=${SRIOV_FEC_DAEMON_IMAGE:-${IMAGE_REGISTRY}/sriov-fec-daemon:${SRIOV_FEC_DAEMON_VERSION}}
