#!/bin/bash

IMAGE_REGISTRY=${N3000_IMAGE_REGISTRY:-docker.io}
SRIOV_FEC_DAEMON_VERSION=${SRIOV_FEC_DAEMON_VERSION:-v1.0.0}

export SRIOV_FEC_DAEMON_IMAGE=${SRIOV_FEC_DAEMON_IMAGE:-${IMAGE_REGISTRY}/sriov-fec-daemon:${SRIOV_FEC_DAEMON_VERSION}}
