#!/bin/bash

IMAGE_REGISTRY=${N3000_IMAGE_REGISTRY:-registry.redhat.io}
IMAGE_VER=${IMAGE_VER:-v1.0.0}

export SRIOV_FEC_LABELER_IMAGE=${SRIOV_FEC_LABELER_IMAGE:-${IMAGE_REGISTRY}/n3000-labeler:${IMAGE_VER}}
export SRIOV_FEC_DAEMON_IMAGE=${SRIOV_FEC_DAEMON_IMAGE:-${IMAGE_REGISTRY}/sriov-fec-daemon:${IMAGE_VER}}
