# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2024 Intel Corporation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - 'get'
  - 'create'
  - 'list'
  - 'update'
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/finalizers
  verbs:
  - 'get'
  - 'create'
  - 'list'
  - 'update'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - 'get'
  - 'create'
  - 'list'
  - 'update'
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - '*'
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecclusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecclusterconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecnodeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecnodeconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sriovvrb.intel.com
  resources:
  - sriovvrbclusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovvrb.intel.com
  resources:
  - sriovvrbclusterconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sriovvrb.intel.com
  resources:
  - sriovvrbnodeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovvrb.intel.com
  resources:
  - sriovvrbnodeconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sriovvrb.intel.com
  resources:
  - sriovvrbnodeconfigs/status
  verbs:
  - get
  - patch
  - update
