# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2025 Intel Corporation

# permissions for end users to edit sriovfecclusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovfecclusterconfig-editor-role
rules:
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecclusterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecclusterconfigs/status
  verbs:
  - get
