# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2024 Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  name: labeler-config
  namespace: {{ .SRIOV_FEC_NAMESPACE }}
immutable: false
data:
  configMap: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: supported-accelerators
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
    immutable: false
    data:
      accelerators.json: |
        {
          "VendorID": {
            "8086": "Intel Corporation",
            "1172": "Altera Corporation"
          },
          "Class": "12",
          "SubClass": "00",
          "Devices": {
            "0d8f": "FPGA_5GNR",
            "5052": "FPGA_LTE",
            "0d5c": "ACC100",
            "57c0": "ACC200",
            "0b32": ""
          },
          "NodeLabel": "fpga.intel.com/intel-accelerator-present"
        }
      accelerators_vrb.json: |
        {
          "VendorID": {
            "8086": "Intel Corporation"
          },
          "Class": "12",
          "SubClass": "00",
          "Devices": {
            "57c0": "VRB1",
            "57c2": "VRB2"
          },
          "NodeLabel": "fpga.intel.com/intel-accelerator-present"
        }
  serviceAccount: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: accelerator-discovery
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
  clusterRole: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: accelerator-discovery
    rules:
    - apiGroups: [""]
      resources: ["nodes"]
      verbs: ["get", "update"]
  clusterRoleBinding: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: accelerator-discovery
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: accelerator-discovery
      {{ if eq (.SRIOV_FEC_GENERIC_K8S|ToLower) `false` }}
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
      {{ end }}
    subjects:
    - kind: ServiceAccount
      name: accelerator-discovery
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
      {{ if eq (.SRIOV_FEC_GENERIC_K8S|ToLower) `false` }}
    userNames:
    - system:serviceaccount:{{ .SRIOV_FEC_NAMESPACE }}:accelerator-discovery
      {{ end }}
  daemonSet: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      labels:
        app: accelerator-discovery
      name: accelerator-discovery
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
    spec:
      minReadySeconds: 10
      selector:
        matchLabels:
          app: accelerator-discovery
      template:
        metadata:
          annotations:
            target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
          labels:
            app: accelerator-discovery
          name: accelerator-discovery
        spec:
          serviceAccount: accelerator-discovery
          serviceAccountName: accelerator-discovery
          containers:
          - image: {{ .SRIOV_FEC_LABELER_IMAGE }}
            imagePullPolicy: IfNotPresent
            name: accelerator-discovery
            securityContext:
              readOnlyRootFilesystem: true
            volumeMounts:
            - name: config-volume
              mountPath: "/labeler-workspace/config"
              readOnly: true
            env:
              - name: NODENAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
          volumes:
            - name: config-volume
              configMap:
                name: supported-accelerators
                items:
                - key: accelerators.json
                  path: accelerators.json
                - key: accelerators_vrb.json
                  path: accelerators_vrb.json
