# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2025 Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  name: device-plugin-config
  namespace: {{ .SRIOV_FEC_NAMESPACE }}
immutable: false
data:
  serviceAccount: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: sriov-device-plugin
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
  role: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: sriov-plugin
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
    rules:
      - apiGroups:
          - security.openshift.io
        resourceNames:
          - privileged
        resources:
          - securitycontextconstraints
        verbs:
          - use
  roleBinding: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: sriov-device-plugin
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: sriov-plugin
    subjects:
      - kind: ServiceAccount
        name: sriov-device-plugin
        namespace: {{ .SRIOV_FEC_NAMESPACE }}
  configMap: |
    apiVersion: v1
    kind: ConfigMap
    immutable: false
    metadata:
      name: sriovdp-config
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
    data:
      config.json: |
        {
            "resourceList": [
                {
                    "resourceName": "{{ .SRIOV_FEC_LTE_RESOURCE_NAME }}",
                    "deviceType": "accelerator",
                    "selectors": {
                        "vendors": ["1172"],
                        "devices": ["5050"],
                        "drivers": ["pci-pf-stub", "vfio-pci", "igb_uio"]
                    },
                    "additionalInfo": {
                      "*": {
                          "VFIO_TOKEN": "{{ .SRIOV_FEC_VFIO_TOKEN }}"
                      }
                     }
                },
                {
                    "resourceName": "{{ .SRIOV_FEC_5G_RESOURCE_NAME }}",
                    "deviceType": "accelerator",
                    "selectors": {
                        "vendors": ["8086"],
                        "devices": ["0d90"],
                        "drivers": ["pci-pf-stub", "vfio-pci", "igb_uio"]
                    },
                    "additionalInfo": {
                      "*": {
                          "VFIO_TOKEN": "{{ .SRIOV_FEC_VFIO_TOKEN }}"
                      }
                     }
                },
                {
                    "resourceName": "{{ .SRIOV_FEC_ACC100_RESOURCE_NAME }}",
                    "deviceType": "accelerator",
                    "selectors": {
                        "vendors": ["8086"],
                        "devices": ["0d5d"],
                        "drivers": ["pci-pf-stub", "vfio-pci", "igb_uio"]
                    },
                    "additionalInfo": {
                      "*": {
                          "VFIO_TOKEN": "{{ .SRIOV_FEC_VFIO_TOKEN }}"
                      }
                     }
                },
                {
                    "resourceName": "{{ .SRIOV_FEC_ACC200_RESOURCE_NAME }}",
                    "deviceType": "accelerator",
                    "selectors": {
                        "vendors": ["8086"],
                        "devices": ["57c1"],
                        "drivers": ["pci-pf-stub", "vfio-pci", "igb_uio"]
                    },
                    "additionalInfo": {
                        "*": {
                              "VFIO_TOKEN": "{{ .SRIOV_FEC_VFIO_TOKEN }}"
                          }
                        }
                },
                {
                    "resourceName": "{{ .SRIOV_FEC_VRB2_RESOURCE_NAME }}",
                    "deviceType": "accelerator",
                    "selectors": {
                        "vendors": ["8086"],
                        "devices": ["57c3"],
                        "drivers": ["pci-pf-stub", "vfio-pci", "igb_uio"]
                    },
                    "additionalInfo": {
                        "*": {
                              "VFIO_TOKEN": "{{ .SRIOV_FEC_VFIO_TOKEN }}"
                          }
                        }
                }
            ]
        }
  daemonSet: |
    kind: DaemonSet
    apiVersion: apps/v1
    metadata:
      name: sriov-device-plugin
      namespace: {{ .SRIOV_FEC_NAMESPACE }}
      labels:
        app: sriov-device-plugin-daemonset
    spec:
      minReadySeconds: 10
      selector:
        matchLabels:
          app: sriov-device-plugin-daemonset
      template:
        metadata:
          labels:
            app: sriov-device-plugin-daemonset
        spec:
          hostNetwork: true
          nodeSelector:
            fpga.intel.com/intel-accelerator-present: ""
          serviceAccountName: sriov-device-plugin
          containers:
          - name: sriov-device-plugin
            image: {{ .SRIOV_FEC_NETWORK_DEVICE_PLUGIN_IMAGE }}
            imagePullPolicy: IfNotPresent
            securityContext:
              readOnlyRootFilesystem: true
              privileged: true
            args:
            - --log-level=10
            volumeMounts:
            - name: devicesock
              mountPath: /var/lib/kubelet/device-plugins
              readOnly: false
            - name: config-volume
              mountPath: /etc/pcidp/
              readOnly: true
          volumes:
            - name: devicesock
              hostPath:
                path: /var/lib/kubelet/device-plugins
            - name: config-volume
              configMap:
                name: sriovdp-config
                items:
                - key: config.json
                  path: config.json
