# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

FROM golang:1.14 as builder

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download

COPY cmd cmd/
COPY pkg pkg/
copy api api/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o n3000_daemon cmd/daemon/main.go

ARG OPAE_VERSION=$OPAE_VERSION
FROM opae:$OPAE_VERSION

RUN yum install -y pciutils ethtool
WORKDIR /
COPY --from=builder /workspace/n3000_daemon .

ENTRYPOINT ["/n3000_daemon"]
