# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation
--- Makefile    2020-06-25 21:48:52.000000000 +0200
+++ Makefile.new        2020-08-12 10:02:38.150906905 +0200
@@ -1,6 +1,7 @@
-KERNELDIR ?= /lib/modules/$(shell uname -r)/build
+KERNELVER ?= $(shell uname -r)
+KERNELDIR = /lib/modules/$(KERNELVER)/build
 PWD ?= $(shell pwd)
-kerval = $(shell uname -r | sed 's/\([0-9]*\.[0-9]*\)\..*/\1/')
+kerval = $(shell echo $$KERNELVER | sed 's/\([0-9]*\.[0-9]*\)\..*/\1/')
 
 cflags-y +=  -Wno-unused-value -Wno-unused-label -I$(M)/include -I$(M)/include/uapi -I$(M)/include/intel
 cflags-y += -I$(M)/build/include -I$(M)/build/include/uapi -I$(M)/build/include/intel
