// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2020 Intel Corporation

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BBDevConfig) DeepCopyInto(out *BBDevConfig) {
	*out = *in
	out.Downlink = in.Downlink
	out.Uplink = in.Uplink
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BBDevConfig.
func (in *BBDevConfig) DeepCopy() *BBDevConfig {
	if in == nil {
		return nil
	}
	out := new(BBDevConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardConfig) DeepCopyInto(out *CardConfig) {
	*out = *in
	out.BBDevConfig = in.BBDevConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardConfig.
func (in *CardConfig) DeepCopy() *CardConfig {
	if in == nil {
		return nil
	}
	out := new(CardConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfig) DeepCopyInto(out *NodeConfig) {
	*out = *in
	if in.Cards != nil {
		in, out := &in.Cards, &out.Cards
		*out = make([]CardConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfig.
func (in *NodeConfig) DeepCopy() *NodeConfig {
	if in == nil {
		return nil
	}
	out := new(NodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInventory) DeepCopyInto(out *NodeInventory) {
	*out = *in
	if in.SriovAccelerators != nil {
		in, out := &in.SriovAccelerators, &out.SriovAccelerators
		*out = make([]SriovAccelerator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInventory.
func (in *NodeInventory) DeepCopy() *NodeInventory {
	if in == nil {
		return nil
	}
	out := new(NodeInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovAccelerator) DeepCopyInto(out *SriovAccelerator) {
	*out = *in
	if in.VFs != nil {
		in, out := &in.VFs, &out.VFs
		*out = make([]VF, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovAccelerator.
func (in *SriovAccelerator) DeepCopy() *SriovAccelerator {
	if in == nil {
		return nil
	}
	out := new(SriovAccelerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecClusterConfig) DeepCopyInto(out *SriovFecClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecClusterConfig.
func (in *SriovFecClusterConfig) DeepCopy() *SriovFecClusterConfig {
	if in == nil {
		return nil
	}
	out := new(SriovFecClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovFecClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecClusterConfigList) DeepCopyInto(out *SriovFecClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SriovFecClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecClusterConfigList.
func (in *SriovFecClusterConfigList) DeepCopy() *SriovFecClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(SriovFecClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovFecClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecClusterConfigSpec) DeepCopyInto(out *SriovFecClusterConfigSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecClusterConfigSpec.
func (in *SriovFecClusterConfigSpec) DeepCopy() *SriovFecClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SriovFecClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecClusterConfigStatus) DeepCopyInto(out *SriovFecClusterConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecClusterConfigStatus.
func (in *SriovFecClusterConfigStatus) DeepCopy() *SriovFecClusterConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SriovFecClusterConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecNodeConfig) DeepCopyInto(out *SriovFecNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecNodeConfig.
func (in *SriovFecNodeConfig) DeepCopy() *SriovFecNodeConfig {
	if in == nil {
		return nil
	}
	out := new(SriovFecNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovFecNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecNodeConfigList) DeepCopyInto(out *SriovFecNodeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SriovFecNodeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecNodeConfigList.
func (in *SriovFecNodeConfigList) DeepCopy() *SriovFecNodeConfigList {
	if in == nil {
		return nil
	}
	out := new(SriovFecNodeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovFecNodeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecNodeConfigSpec) DeepCopyInto(out *SriovFecNodeConfigSpec) {
	*out = *in
	if in.Cards != nil {
		in, out := &in.Cards, &out.Cards
		*out = make([]CardConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecNodeConfigSpec.
func (in *SriovFecNodeConfigSpec) DeepCopy() *SriovFecNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SriovFecNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecNodeConfigStatus) DeepCopyInto(out *SriovFecNodeConfigStatus) {
	*out = *in
	in.Inventory.DeepCopyInto(&out.Inventory)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecNodeConfigStatus.
func (in *SriovFecNodeConfigStatus) DeepCopy() *SriovFecNodeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SriovFecNodeConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UplinkDownlink) DeepCopyInto(out *UplinkDownlink) {
	*out = *in
	out.Queues = in.Queues
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UplinkDownlink.
func (in *UplinkDownlink) DeepCopy() *UplinkDownlink {
	if in == nil {
		return nil
	}
	out := new(UplinkDownlink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UplinkDownlinkQueues) DeepCopyInto(out *UplinkDownlinkQueues) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UplinkDownlinkQueues.
func (in *UplinkDownlinkQueues) DeepCopy() *UplinkDownlinkQueues {
	if in == nil {
		return nil
	}
	out := new(UplinkDownlinkQueues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VF) DeepCopyInto(out *VF) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VF.
func (in *VF) DeepCopy() *VF {
	if in == nil {
		return nil
	}
	out := new(VF)
	in.DeepCopyInto(out)
	return out
}
