// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardConfig) DeepCopyInto(out *CardConfig) {
	*out = *in
	out.QueuesConfiguration = in.QueuesConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardConfig.
func (in *CardConfig) DeepCopy() *CardConfig {
	if in == nil {
		return nil
	}
	out := new(CardConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardQueues) DeepCopyInto(out *CardQueues) {
	*out = *in
	out.Downlink = in.Downlink
	out.Uplink = in.Uplink
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardQueues.
func (in *CardQueues) DeepCopy() *CardQueues {
	if in == nil {
		return nil
	}
	out := new(CardQueues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfig) DeepCopyInto(out *NodeConfig) {
	*out = *in
	if in.Cards != nil {
		in, out := &in.Cards, &out.Cards
		*out = make([]CardConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfig.
func (in *NodeConfig) DeepCopy() *NodeConfig {
	if in == nil {
		return nil
	}
	out := new(NodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecClusterConfig) DeepCopyInto(out *SriovFecClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecClusterConfig.
func (in *SriovFecClusterConfig) DeepCopy() *SriovFecClusterConfig {
	if in == nil {
		return nil
	}
	out := new(SriovFecClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovFecClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecClusterConfigList) DeepCopyInto(out *SriovFecClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SriovFecClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecClusterConfigList.
func (in *SriovFecClusterConfigList) DeepCopy() *SriovFecClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(SriovFecClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovFecClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecClusterConfigSpec) DeepCopyInto(out *SriovFecClusterConfigSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecClusterConfigSpec.
func (in *SriovFecClusterConfigSpec) DeepCopy() *SriovFecClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SriovFecClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecClusterConfigStatus) DeepCopyInto(out *SriovFecClusterConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecClusterConfigStatus.
func (in *SriovFecClusterConfigStatus) DeepCopy() *SriovFecClusterConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SriovFecClusterConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecNodeConfig) DeepCopyInto(out *SriovFecNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecNodeConfig.
func (in *SriovFecNodeConfig) DeepCopy() *SriovFecNodeConfig {
	if in == nil {
		return nil
	}
	out := new(SriovFecNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovFecNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecNodeConfigList) DeepCopyInto(out *SriovFecNodeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SriovFecNodeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecNodeConfigList.
func (in *SriovFecNodeConfigList) DeepCopy() *SriovFecNodeConfigList {
	if in == nil {
		return nil
	}
	out := new(SriovFecNodeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovFecNodeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecNodeConfigSpec) DeepCopyInto(out *SriovFecNodeConfigSpec) {
	*out = *in
	if in.Cards != nil {
		in, out := &in.Cards, &out.Cards
		*out = make([]CardConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecNodeConfigSpec.
func (in *SriovFecNodeConfigSpec) DeepCopy() *SriovFecNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SriovFecNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovFecNodeConfigStatus) DeepCopyInto(out *SriovFecNodeConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovFecNodeConfigStatus.
func (in *SriovFecNodeConfigStatus) DeepCopy() *SriovFecNodeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SriovFecNodeConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UplinkDownlink) DeepCopyInto(out *UplinkDownlink) {
	*out = *in
	out.Queues = in.Queues
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UplinkDownlink.
func (in *UplinkDownlink) DeepCopy() *UplinkDownlink {
	if in == nil {
		return nil
	}
	out := new(UplinkDownlink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UplinkDownlinkQueues) DeepCopyInto(out *UplinkDownlinkQueues) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UplinkDownlinkQueues.
func (in *UplinkDownlinkQueues) DeepCopy() *UplinkDownlinkQueues {
	if in == nil {
		return nil
	}
	out := new(UplinkDownlinkQueues)
	in.DeepCopyInto(out)
	return out
}
