//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2020-2023 Intel Corporation

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ACC100BBDevConfig) DeepCopyInto(out *ACC100BBDevConfig) {
	*out = *in
	out.Uplink4G = in.Uplink4G
	out.Downlink4G = in.Downlink4G
	out.Uplink5G = in.Uplink5G
	out.Downlink5G = in.Downlink5G
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ACC100BBDevConfig.
func (in *ACC100BBDevConfig) DeepCopy() *ACC100BBDevConfig {
	if in == nil {
		return nil
	}
	out := new(ACC100BBDevConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorSelector) DeepCopyInto(out *AcceleratorSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorSelector.
func (in *AcceleratorSelector) DeepCopy() *AcceleratorSelector {
	if in == nil {
		return nil
	}
	out := new(AcceleratorSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BBDevConfig) DeepCopyInto(out *BBDevConfig) {
	*out = *in
	if in.VRB1 != nil {
		in, out := &in.VRB1, &out.VRB1
		*out = new(VRB1BBDevConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BBDevConfig.
func (in *BBDevConfig) DeepCopy() *BBDevConfig {
	if in == nil {
		return nil
	}
	out := new(BBDevConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ByPriority) DeepCopyInto(out *ByPriority) {
	{
		in := &in
		*out = make(ByPriority, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ByPriority.
func (in ByPriority) DeepCopy() ByPriority {
	if in == nil {
		return nil
	}
	out := new(ByPriority)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInventory) DeepCopyInto(out *NodeInventory) {
	*out = *in
	if in.SriovAccelerators != nil {
		in, out := &in.SriovAccelerators, &out.SriovAccelerators
		*out = make([]SriovAccelerator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInventory.
func (in *NodeInventory) DeepCopy() *NodeInventory {
	if in == nil {
		return nil
	}
	out := new(NodeInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalFunctionConfig) DeepCopyInto(out *PhysicalFunctionConfig) {
	*out = *in
	in.BBDevConfig.DeepCopyInto(&out.BBDevConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalFunctionConfig.
func (in *PhysicalFunctionConfig) DeepCopy() *PhysicalFunctionConfig {
	if in == nil {
		return nil
	}
	out := new(PhysicalFunctionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalFunctionConfigExt) DeepCopyInto(out *PhysicalFunctionConfigExt) {
	*out = *in
	in.BBDevConfig.DeepCopyInto(&out.BBDevConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalFunctionConfigExt.
func (in *PhysicalFunctionConfigExt) DeepCopy() *PhysicalFunctionConfigExt {
	if in == nil {
		return nil
	}
	out := new(PhysicalFunctionConfigExt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueGroupConfig) DeepCopyInto(out *QueueGroupConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueGroupConfig.
func (in *QueueGroupConfig) DeepCopy() *QueueGroupConfig {
	if in == nil {
		return nil
	}
	out := new(QueueGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovAccelerator) DeepCopyInto(out *SriovAccelerator) {
	*out = *in
	if in.VFs != nil {
		in, out := &in.VFs, &out.VFs
		*out = make([]VF, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovAccelerator.
func (in *SriovAccelerator) DeepCopy() *SriovAccelerator {
	if in == nil {
		return nil
	}
	out := new(SriovAccelerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VF) DeepCopyInto(out *VF) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VF.
func (in *VF) DeepCopy() *VF {
	if in == nil {
		return nil
	}
	out := new(VF)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VRB1BBDevConfig) DeepCopyInto(out *VRB1BBDevConfig) {
	*out = *in
	out.ACC100BBDevConfig = in.ACC100BBDevConfig
	out.QFFT = in.QFFT
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VRB1BBDevConfig.
func (in *VRB1BBDevConfig) DeepCopy() *VRB1BBDevConfig {
	if in == nil {
		return nil
	}
	out := new(VRB1BBDevConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *VRB2BBDevConfig) DeepCopyInto(out *VRB2BBDevConfig) {
	*out = *in
	out.ACC100BBDevConfig = in.ACC100BBDevConfig
	out.QFFT = in.QFFT
	out.QMLD = in.QMLD
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VRB1BBDevConfig.
func (in *VRB2BBDevConfig) DeepCopy() *VRB2BBDevConfig {
	if in == nil {
		return nil
	}
	out := new(VRB2BBDevConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovVrbClusterConfig) DeepCopyInto(out *SriovVrbClusterConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovVrbClusterConfig.
func (in *SriovVrbClusterConfig) DeepCopy() *SriovVrbClusterConfig {
	if in == nil {
		return nil
	}
	out := new(SriovVrbClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovVrbClusterConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovVrbClusterConfigList) DeepCopyInto(out *SriovVrbClusterConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SriovVrbClusterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovVrbClusterConfigList.
func (in *SriovVrbClusterConfigList) DeepCopy() *SriovVrbClusterConfigList {
	if in == nil {
		return nil
	}
	out := new(SriovVrbClusterConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovVrbClusterConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovVrbClusterConfigSpec) DeepCopyInto(out *SriovVrbClusterConfigSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.AcceleratorSelector = in.AcceleratorSelector
	in.PhysicalFunction.DeepCopyInto(&out.PhysicalFunction)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovVrbClusterConfigSpec.
func (in *SriovVrbClusterConfigSpec) DeepCopy() *SriovVrbClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SriovVrbClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovVrbClusterConfigStatus) DeepCopyInto(out *SriovVrbClusterConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovVrbClusterConfigStatus.
func (in *SriovVrbClusterConfigStatus) DeepCopy() *SriovVrbClusterConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SriovVrbClusterConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovVrbNodeConfig) DeepCopyInto(out *SriovVrbNodeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovVrbNodeConfig.
func (in *SriovVrbNodeConfig) DeepCopy() *SriovVrbNodeConfig {
	if in == nil {
		return nil
	}
	out := new(SriovVrbNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovVrbNodeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovVrbNodeConfigList) DeepCopyInto(out *SriovVrbNodeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SriovVrbNodeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovVrbNodeConfigList.
func (in *SriovVrbNodeConfigList) DeepCopy() *SriovVrbNodeConfigList {
	if in == nil {
		return nil
	}
	out := new(SriovVrbNodeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SriovVrbNodeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovVrbNodeConfigSpec) DeepCopyInto(out *SriovVrbNodeConfigSpec) {
	*out = *in
	if in.PhysicalFunctions != nil {
		in, out := &in.PhysicalFunctions, &out.PhysicalFunctions
		*out = make([]PhysicalFunctionConfigExt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovVrbNodeConfigSpec.
func (in *SriovVrbNodeConfigSpec) DeepCopy() *SriovVrbNodeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SriovVrbNodeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SriovVrbNodeConfigStatus) DeepCopyInto(out *SriovVrbNodeConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Inventory.DeepCopyInto(&out.Inventory)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SriovVrbNodeConfigStatus.
func (in *SriovVrbNodeConfigStatus) DeepCopy() *SriovVrbNodeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SriovVrbNodeConfigStatus)
	in.DeepCopyInto(out)
	return out
}
